var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/_fc398b9c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f8526382._.js")
R.c("server/chunks/ssr/_7e597ad3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__219c9d58._.js")
R.c("server/chunks/ssr/[root-of-the-server]__019c8b77._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f2e0462a._.js")
R.c("server/chunks/ssr/1dff6_next_dist_client_components_builtin_global-error_66953fd8.js")
R.c("server/chunks/ssr/[root-of-the-server]__8c53580b._.js")
R.c("server/chunks/ssr/1dff6_next_dist_client_components_9e67838b._.js")
R.c("server/chunks/ssr/1dff6_next_dist_client_components_builtin_forbidden_ffd215e8.js")
R.c("server/chunks/ssr/1dff6_next_dist_client_components_builtin_unauthorized_cc7a8467.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_39d4fc33.js")
R.m(47042)
module.exports=R.m(47042).exports
